import type { OperationItem } from "./types";

/** 개발/테스트용 목 작전 데이터 */
export const mockOperations: OperationItem[] = [
  {
    id: "op-main-001",
    title: "시즌 1 — 심층 구역 이상 징후",
    type: "operation",
    status: "live",
    teamA: [
      { id: "ch-001", name: "카이 안데르센" },
      { id: "ch-002", name: "아마츠키 레이" },
    ],
    teamB: [
      { id: "ch-003", name: "나디아 볼코프" },
      { id: "ch-004", name: "시온 파크" },
    ],
    host: { id: "admin-001", name: "HELIOS" },
    summary: "HELIOS 최우선 작전 지시. 심층 구역 비정상 공명 감지. 전 요원 소집.",
    maxParticipants: 12,
    createdAt: "2026-02-15T09:00:00Z",
    isMainStory: true,
  },
  {
    id: "op-001",
    title: "구역 7-B 정찰 작전",
    type: "operation",
    status: "live",
    teamA: [
      { id: "ch-001", name: "카이 안데르센" },
      { id: "ch-002", name: "아마츠키 레이" },
    ],
    teamB: [{ id: "ch-003", name: "나디아 볼코프" }],
    host: { id: "ch-001", name: "카이 안데르센" },
    summary: "외곽 구역 비동조 신호 탐지. 정찰 및 무력화 임무.",
    maxParticipants: 4,
    createdAt: "2026-02-18T06:30:00Z",
  },
  {
    id: "op-002",
    title: "중앙 아케이드 야간 순찰",
    type: "downtime",
    status: "waiting",
    teamA: [],
    teamB: [],
    host: { id: "ch-003", name: "나디아 볼코프" },
    summary: "민간 구역 순찰 중 발생하는 일상적 교류.",
    maxParticipants: 6,
    createdAt: "2026-02-18T05:48:00Z",
  },
  {
    id: "op-003",
    title: "지하 통로 토벌전",
    type: "operation",
    status: "waiting",
    teamA: [{ id: "ch-005", name: "레이 노바크" }],
    teamB: [
      { id: "ch-006", name: "엘라 크루즈" },
      { id: "ch-007", name: "진 하야시" },
    ],
    host: { id: "ch-005", name: "레이 노바크" },
    summary: "지하 통로에 은거 중인 적대 세력 소탕. 2대1 비대칭 전투.",
    maxParticipants: 4,
    createdAt: "2026-02-17T14:20:00Z",
  },
  {
    id: "op-004",
    title: "보안국 내부 면담",
    type: "downtime",
    status: "waiting",
    teamA: [],
    teamB: [],
    host: { id: "ch-004", name: "시온 파크" },
    summary: "SBCS 내부 기밀 면담. 초대 필요.",
    maxParticipants: 3,
    createdAt: "2026-02-17T10:00:00Z",
  },
  {
    id: "op-005",
    title: "외곽 지구 전면 공세",
    type: "operation",
    status: "completed",
    teamA: [{ id: "ch-002", name: "아마츠키 레이" }],
    teamB: [{ id: "ch-005", name: "레이 노바크" }],
    host: { id: "ch-002", name: "아마츠키 레이" },
    summary: "Static 거점 확인 및 제압 완료. 사후 보고 대기.",
    maxParticipants: 4,
    createdAt: "2026-02-16T08:00:00Z",
  },
  {
    id: "op-006",
    title: "심층 구역 잠입 조사",
    type: "downtime",
    status: "completed",
    teamA: [],
    teamB: [],
    host: { id: "ch-006", name: "엘라 크루즈" },
    summary: "비밀 연구 시설 내부 정보 수집 완료.",
    maxParticipants: 2,
    createdAt: "2026-02-15T20:00:00Z",
  },
  {
    id: "op-007",
    title: "네온 구역 합동 순찰",
    type: "operation",
    status: "completed",
    teamA: [
      { id: "ch-001", name: "카이 안데르센" },
      { id: "ch-004", name: "시온 파크" },
    ],
    teamB: [
      { id: "ch-003", name: "나디아 볼코프" },
      { id: "ch-007", name: "진 하야시" },
    ],
    host: { id: "ch-001", name: "카이 안데르센" },
    summary: "네온 구역 Static 활동 징후 수색. 2v2 교전 종료.",
    maxParticipants: 4,
    createdAt: "2026-02-14T16:00:00Z",
  },
  {
    id: "op-008",
    title: "주거 구역 B-12 교류회",
    type: "downtime",
    status: "waiting",
    teamA: [],
    teamB: [],
    host: { id: "ch-007", name: "진 하야시" },
    summary: "비번 요원 간 비공식 교류. 누구나 참가 가능.",
    maxParticipants: 8,
    createdAt: "2026-02-18T02:00:00Z",
  },
];
