import type { OperationItem } from "./types";

/** 개발/테스트용 목 작전 데이터 */
export const mockOperations: OperationItem[] = [
  {
    id: "op-001",
    title: "구역 7-B 정찰 작전",
    type: "전투",
    status: "대기중",
    participants: 2,
    maxParticipants: 4,
    host: "카이 안데르센",
    summary: "외곽 구역 비동조 신호 탐지. 정찰 및 무력화 임무.",
  },
  {
    id: "op-002",
    title: "중앙 아케이드 야간 순찰",
    type: "RP",
    status: "진행중",
    participants: 3,
    maxParticipants: 6,
    host: "나디아 볼코프",
    summary: "민간 구역 순찰 중 발생하는 일상적 교류.",
  },
  {
    id: "op-003",
    title: "지하 통로 토벌전",
    type: "전투",
    status: "진행중",
    participants: 4,
    maxParticipants: 4,
    host: "레이 노바크",
    summary: "지하 통로에 은거 중인 적대 세력 소탕.",
  },
  {
    id: "op-004",
    title: "보안국 내부 면담",
    type: "RP",
    status: "대기중",
    participants: 1,
    maxParticipants: 3,
    host: "시온 파크",
    summary: "SBCS 내부 기밀 면담. 초대 필요.",
  },
  {
    id: "op-005",
    title: "외곽 지구 전면 공세",
    type: "전투",
    status: "완료",
    participants: 4,
    maxParticipants: 4,
    host: "아마츠키 레이",
    summary: "Static 거점 확인 및 제압 완료. 사후 보고 대기.",
  },
  {
    id: "op-006",
    title: "심층 구역 잠입 조사",
    type: "RP",
    status: "완료",
    participants: 2,
    maxParticipants: 2,
    host: "엘라 크루즈",
    summary: "비밀 연구 시설 내부 정보 수집 완료.",
  },
];
